import { Prompt, Lora } from "next/font/google";
import "../globals.css";
import Navigation from "../components/Navigation";
import Footersection from '../components/Footersection';
import BinaryCursorTrail from "../components/BinaryCursorTrail"; 

const prompt = Prompt({
  subsets: ["thai", "latin"],
  weight: ["300", "400", "700"],
  variable: "--font-prompt", 
});

const lora = Lora({
  subsets: ["latin"],
  weight: ["400", "500"],
  style: ["italic"],
  variable: "--font-lora", 
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${prompt.variable} ${lora.variable} h-full antialiased`}
    >
      <body className={`${prompt.className} bg-gray-100 min-h-screen flex flex-col`}>
        <Navigation />
        
        <main className="flex-grow">
          {children}
        </main>
        
        <Footersection />
        
        <BinaryCursorTrail />
      </body>
    </html>
  );
}
